version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=NOME_DO_ADMIN_DO_BD
      - POSTGRES_PASSWORD=SENHA_AQUI
    ports:
      - '15432:5432' # Nesse caso pode ser 5432:5432 também 
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
